imagenet_path: imagenet/
alexnet:
  epochs: 90
  batch_size: 32
  lr: 1.0e-2
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_step_size: 30
  lr_gamma: 0.1
convnext:
  epochs: 45
  batch_size: 64
  lr: 1.0e-2
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_step_size: 30
  lr_gamma: 0.1
